//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameProj.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class GameDataBase : DbContext
    {
        public GameDataBase()
            : base("name=GameDataBase")
        {
        }
    
        public virtual DbSet<ARTIST> ARTISTs { get; set; }
        public virtual DbSet<DEVELOPER> DEVELOPERs { get; set; }
        public virtual DbSet<GAME> GAMES { get; set; }
        public virtual DbSet<GAMESINPROCESS> GAMESINPROCESSes { get; set; }
        public virtual DbSet<MANAGER> MANAGERs { get; set; }
        public virtual DbSet<TEAM_ARTST> TEAM_ARTST { get; set; }
        public virtual DbSet<TEAM_DVLP> TEAM_DVLP { get; set; }
        
    }
}
