//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAME
    {
        public int ID_GAMES { get; set; }
        public string NAME { get; set; }
        public Nullable<System.DateTime> STARTCREATING { get; set; }
        public Nullable<System.DateTime> ENDCREATING { get; set; }
        public Nullable<int> PROFIT { get; set; }
        public Nullable<int> TEAM_ID_DVLP { get; set; }
        public Nullable<int> MANAGER_ID { get; set; }
        public Nullable<int> MANAGERPR_ID { get; set; }
        public Nullable<int> RATE { get; set; }
    
        public virtual MANAGER MANAGER { get; set; }
        public virtual MANAGER MANAGER1 { get; set; }
        public virtual TEAM_DVLP TEAM_DVLP { get; set; }
    }
}
