//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GAMESINPROCESS
    {
        public int GAMESINPROCESS_ID { get; set; }
        public string NAME { get; set; }
        public Nullable<int> TEAM_ID_DVLP { get; set; }
        public Nullable<int> TEAM_ID_ARTST { get; set; }
        public Nullable<System.DateTime> STARTCREATING { get; set; }
    
        public virtual TEAM_DVLP TEAM_DVLP { get; set; }
        public virtual TEAM_ARTST TEAM_ARTST { get; set; }
    }
}
