-- ¡ƒ ‘»–Ã€ œŒ œ–Œ»«¬Œƒ—“¬”  ŒÃœ‹ﬁ“≈–Õ€’ »√–

GO
CREATE DATABASE DEMASSSSSS
GO
USE DEMASSSSSS

GO
-- —œ»—Œ   ŒÃ¿Õƒ –¿«–¿¡Œ“◊» Œ¬
CREATE TABLE TEAM_DVLP
(
	TEAM_DVLP_ID INT PRIMARY KEY IDENTITY,
	NAME VARCHAR(100)
)

GO
-- —œ»—Œ   ŒÃ¿Õƒ ’”ƒŒ∆Õ» Œ¬
CREATE TABLE TEAM_ARTST
(
	TEAM_ARTST_ID INT PRIMARY KEY IDENTITY,
	NAME VARCHAR(100)
)

GO
-- Ã≈Õ≈ƒ∆≈–
CREATE TABLE MANAGER
(
    MANAGER_ID INT PRIMARY KEY IDENTITY,
	FIO_MNG NVARCHAR(60),
	SALARY_MNG INT
)

GO
-- —œ»—Œ  ¬€œ”Ÿ≈ÕÕ€’ »√–
CREATE TABLE GAMES
(
	ID_GAMES INT PRIMARY KEY IDENTITY,
	NAME VARCHAR(100),
	STARTCREATING DATE,
	ENDCREATING DATE,
	PROFIT INT,
	TEAM_ID_DVLP INT REFERENCES TEAM_DVLP(TEAM_DVLP_ID),
	MANAGER_ID INT REFERENCES MANAGER(MANAGER_ID),
	MANAGERPR_ID INT REFERENCES MANAGER(MANAGER_ID),
	RATE INT
)

GO
-- —œ»—Œ  »√– ¬ –¿«–¿¡Œ“ ≈
CREATE TABLE GAMESINPROCESS
(
    GAMESINPROCESS_ID INT PRIMARY KEY IDENTITY,
	NAME VARCHAR(100),
	TEAM_ID_DVLP INT REFERENCES TEAM_DVLP(TEAM_DVLP_ID),
	TEAM_ID_ARTST INT REFERENCES TEAM_ARTST(TEAM_ARTST_ID),
	STARTCREATING DATE,
) 

GO
-- –¿«–¿¡Œ“◊» 
CREATE TABLE DEVELOPER
(
	DVLP_ID INT PRIMARY KEY IDENTITY,
	FIO_DVLP NVARCHAR(60),
	PASSPORT_DVLP NVARCHAR(20),
	LNG NVARCHAR(5),
	SALARY_DVLP INT,
	LEADER BIT,
	EXPERIENCE INT,
	EDUCATION NVARCHAR(30),
	TEAM_ID_DVLP INT REFERENCES TEAM_DVLP(TEAM_DVLP_ID),
)

GO
-- ’”ƒŒ∆Õ» 
CREATE TABLE ARTIST
(
	ARTST_ID INT PRIMARY KEY IDENTITY,
	FIO_ARTST NVARCHAR(60),
	PASSPORT_ARTST NVARCHAR(20),
	SALARY_ARTST INT,
	TEAM_ID_ARTST INT REFERENCES TEAM_ARTST(TEAM_ARTST_ID)
)

-- »Õ—≈–“€
INSERT INTO TEAM_DVLP (NAME) VALUES ('VALVE');
INSERT INTO TEAM_DVLP (NAME) VALUES ('UBISOFT');
INSERT INTO TEAM_DVLP (NAME) VALUES ('EA');

INSERT INTO TEAM_ARTST (NAME) VALUES ('BLACK');
INSERT INTO TEAM_ARTST (NAME) VALUES ('WHITE');
INSERT INTO TEAM_ARTST (NAME) VALUES ('YELLOW');

INSERT INTO MANAGER (FIO_MNG, SALARY_MNG) VALUES ('M_œÓ„ÓÏËÈ', 32500);
INSERT INTO MANAGER (FIO_MNG, SALARY_MNG) VALUES ('M_◊Ûı‡È', 27500);
INSERT INTO MANAGER (FIO_MNG, SALARY_MNG) VALUES ('M_ Óˆ˛·ËÌÒÍËÈ', 20000);

INSERT INTO GAMES (NAME, STARTCREATING, ENDCREATING, PROFIT, TEAM_ID_DVLP, MANAGER_ID, MANAGERPR_ID, RATE) VALUES ('HALF_LIFE', '10/10/2015', '11/11/2016', 2500000, 1, 1, 1, 8);
INSERT INTO GAMES (NAME, STARTCREATING, ENDCREATING, PROFIT, TEAM_ID_DVLP, MANAGER_ID, MANAGERPR_ID, RATE) VALUES ('ARTIFACT', '5/5/2017', '6/6/2019', 100000, 2, 2, 2, 5);
INSERT INTO GAMES (NAME, STARTCREATING, ENDCREATING, PROFIT, TEAM_ID_DVLP, MANAGER_ID, MANAGERPR_ID, RATE) VALUES ('DBD', '2/2/2012', '1/1/2016', 75000000, 3, 3, 3, 10);

INSERT INTO GAMESINPROCESS (NAME, TEAM_ID_DVLP, TEAM_ID_ARTST, STARTCREATING) VALUES ('STALKER_3', 1, 1, '2/2/2002');
INSERT INTO GAMESINPROCESS (NAME, TEAM_ID_DVLP, TEAM_ID_ARTST, STARTCREATING) VALUES ('SUBNAUTICA', 3, 2, '12/12/2012');
INSERT INTO GAMESINPROCESS (NAME, TEAM_ID_DVLP, TEAM_ID_ARTST,STARTCREATING) VALUES ('POE_2', 2, 3, '4/4/2004');

INSERT INTO DEVELOPER (FIO_DVLP, PASSPORT_DVLP, LNG, SALARY_DVLP, LEADER, EXPERIENCE, EDUCATION, TEAM_ID_DVLP) VALUES ('D_—ÚÂÔ‡ÌÓ‚', '40 14 228337', 'C++', 150000, 1, 8, 'HIGHER', 3);
INSERT INTO DEVELOPER (FIO_DVLP, PASSPORT_DVLP, LNG, SALARY_DVLP, LEADER, EXPERIENCE, EDUCATION,TEAM_ID_DVLP) VALUES ('D_≈¯Ó‚', '20 14 334552', 'C#', 95000, 0, 2, 'LOWER', 2);
INSERT INTO DEVELOPER (FIO_DVLP, PASSPORT_DVLP, LNG, SALARY_DVLP, LEADER, EXPERIENCE, EDUCATION, TEAM_ID_DVLP) VALUES ('D_”ÒÚËÌÓ‚ ', '10 95 887755', 'RUBY', 75000, 0, 2, 'MEDIUM', 2);

INSERT INTO ARTIST (FIO_ARTST , PASSPORT_ARTST , SALARY_ARTST, TEAM_ID_ARTST) VALUES ('A_“ËÚÓ‚', '32 25 546989', 40000, 2);
INSERT INTO ARTIST (FIO_ARTST , PASSPORT_ARTST , SALARY_ARTST, TEAM_ID_ARTST) VALUES ('A_¡Ó·˚Î∏‚ ', '24 42 885774', 15000, 3);
INSERT INTO ARTIST (FIO_ARTST , PASSPORT_ARTST , SALARY_ARTST, TEAM_ID_ARTST) VALUES ('A_¡ÎÓıËÌ', '32 56 554969', 20000, 1);

-- «¿œ–Œ—€

GO
-- 1 Ì‡ ‡·Ó˜ÂÂ ‚ÂÏˇ
SELECT DISTINCT GAMES.NAME, GAMES.PROFIT, DATEDIFF(MONTH, GAMES.STARTCREATING, GAMES.ENDCREATING) AS MONTH_CREATING
FROM GAMES, MANAGER, DEVELOPER, ARTIST;

-- 2

GO
-- 3 Ì‡ ˇÁ˚Í
CREATE PROCEDURE SelectLan
@lan VARCHAR(20)
AS
SELECT DISTINCT DEVELOPER.FIO_DVLP, GAMES.NAME, DEVELOPER.SALARY_DVLP
FROM DEVELOPER, GAMES
WHERE DEVELOPER.LNG = @lan AND GAMES.TEAM_ID_DVLP = DEVELOPER.TEAM_ID_DVLP;

GO
SelectLan'C#'

GO
-- 4 Ì‡ ÂÈÚËÌ„
SELECT DISTINCT DEVELOPER.FIO_DVLP, GAMES.NAME, GAMES.RATE
FROM DEVELOPER, GAMES
WHERE GAMES.TEAM_ID_DVLP = DEVELOPER.TEAM_ID_DVLP
ORDER BY GAMES.RATE DESC;

GO
-- ¬€¬Œƒ
SELECT* FROM TEAM_DVLP;
SELECT* FROM TEAM_ARTST;
SELECT* FROM MANAGER;
SELECT* FROM GAMES;
SELECT* FROM GAMESINPROCESS;
SELECT* FROM DEVELOPER;
SELECT* FROM ARTIST;

GO
-- “–»√√≈–
CREATE TRIGGER TRIG
ON DEVELOPER AFTER INSERT
AS
BEGIN
DECLARE @ID INT
DECLARE @EXP INT
SELECT @ID = DVLP_ID FROM DEVELOPER
SELECT @EXP = EXPERIENCE FROM DEVELOPER
IF (@EXP <= 2)
BEGIN
UPDATE DEVELOPER
SET EDUCATION = 'LOWER'
WHERE DVLP_ID = @ID
END
END

GO
CREATE TRIGGER TRIG2
ON DEVELOPER AFTER Update
AS
BEGIN
DECLARE @ID INT
DECLARE @EXP INT
SELECT @ID = i.DVLP_ID FROM inserted i
SELECT @EXP = i.EXPERIENCE FROM inserted i WHERE DVLP_ID = @ID
IF (@EXP <= 2)
BEGIN
UPDATE DEVELOPER
SET EDUCATION = 'LOWER'
WHERE DVLP_ID = @ID
END
END

-- ƒ–Œœ€
DROP TABLE GAMES
DROP TABLE GAMESINPROCESS
DROP TABLE DEVELOPER
DROP TABLE TEAM_DVLP
DROP TABLE ARTIST
DROP TABLE TEAM_ARTST
DROP TABLE MANAGER